<?php

return [
    'title' => 'የአመክሮ አሰጣጥ በተመለከተ',
    'rows' => [
        ['no' => 1, 'sentence' => '1 ወር', 'deducted' => ['year' => '-', 'month' => '-', 'day' => '-'], 'served' => ['year' => '-', 'month' => '-', 'day' => '-']],
        ['no' => 2, 'sentence' => '2 ወር', 'deducted' => ['year' => '-', 'month' => '-', 'day' => '-'], 'served' => ['year' => '-', 'month' => '-', 'day' => '-']],
        ['no' => 3, 'sentence' => '3 ወር', 'deducted' => ['year' => '-', 'month' => '1', 'day' => '-'], 'served' => ['year' => '-', 'month' => '2', 'day' => '-']],
        ['no' => 4, 'sentence' => '4 ወር', 'deducted' => ['year' => '-', 'month' => '1', 'day' => '10'], 'served' => ['year' => '-', 'month' => '3', 'day' => '20']],
        ['no' => 5, 'sentence' => '5 ወር', 'deducted' => ['year' => '-', 'month' => '1', 'day' => '20'], 'served' => ['year' => '-', 'month' => '3', 'day' => '10']],
        ['no' => 6, 'sentence' => '6 ወር', 'deducted' => ['year' => '-', 'month' => '2', 'day' => '-'], 'served' => ['year' => '-', 'month' => '4', 'day' => '-']],
        ['no' => 7, 'sentence' => '7 ወር', 'deducted' => ['year' => '-', 'month' => '2', 'day' => '10'], 'served' => ['year' => '-', 'month' => '4', 'day' => '20']],
        ['no' => 8, 'sentence' => '8 ወር', 'deducted' => ['year' => '-', 'month' => '2', 'day' => '20'], 'served' => ['year' => '-', 'month' => '5', 'day' => '10']],
        ['no' => 9, 'sentence' => '9 ወር', 'deducted' => ['year' => '-', 'month' => '3', 'day' => '-'], 'served' => ['year' => '-', 'month' => '6', 'day' => '-']],
        ['no' => 10, 'sentence' => '10 ወር', 'deducted' => ['year' => '-', 'month' => '3', 'day' => '10'], 'served' => ['year' => '-', 'month' => '6', 'day' => '20']],
        ['no' => 11, 'sentence' => '11 ወር', 'deducted' => ['year' => '-', 'month' => '3', 'day' => '20'], 'served' => ['year' => '-', 'month' => '7', 'day' => '10']],
        ['no' => 12, 'sentence' => '1 ዓመት', 'deducted' => ['year' => '-', 'month' => '4', 'day' => '-'], 'served' => ['year' => '-', 'month' => '8', 'day' => '-']],
        ['no' => 13, 'sentence' => '2 ዓመት', 'deducted' => ['year' => '-', 'month' => '8', 'day' => '-'], 'served' => ['year' => '1', 'month' => '4', 'day' => '-']],
        ['no' => 14, 'sentence' => '3 ዓመት', 'deducted' => ['year' => '1', 'month' => '-', 'day' => '-'], 'served' => ['year' => '2', 'month' => '-', 'day' => '-']],
        ['no' => 15, 'sentence' => '4 ዓመት', 'deducted' => ['year' => '1', 'month' => '4', 'day' => '-'], 'served' => ['year' => '2', 'month' => '8', 'day' => '-']],
        ['no' => 16, 'sentence' => '5 ዓመት', 'deducted' => ['year' => '1', 'month' => '8', 'day' => '-'], 'served' => ['year' => '3', 'month' => '4', 'day' => '-']],
        ['no' => 17, 'sentence' => '6 ዓመት', 'deducted' => ['year' => '2', 'month' => '-', 'day' => '-'], 'served' => ['year' => '4', 'month' => '-', 'day' => '-']],
        ['no' => 18, 'sentence' => '7 ዓመት', 'deducted' => ['year' => '2', 'month' => '4', 'day' => '-'], 'served' => ['year' => '4', 'month' => '8', 'day' => '-']],
        ['no' => 19, 'sentence' => '8 ዓመት', 'deducted' => ['year' => '2', 'month' => '8', 'day' => '-'], 'served' => ['year' => '5', 'month' => '4', 'day' => '-']],
        ['no' => 20, 'sentence' => '9 ዓመት', 'deducted' => ['year' => '3', 'month' => '-', 'day' => '-'], 'served' => ['year' => '6', 'month' => '-', 'day' => '-']],
        ['no' => 21, 'sentence' => '10 ዓመት', 'deducted' => ['year' => '3', 'month' => '4', 'day' => '-'], 'served' => ['year' => '6', 'month' => '8', 'day' => '-']],
        ['no' => 22, 'sentence' => '11 ዓመት', 'deducted' => ['year' => '3', 'month' => '8', 'day' => '-'], 'served' => ['year' => '7', 'month' => '4', 'day' => '-']],
        ['no' => 23, 'sentence' => '12 ዓመት', 'deducted' => ['year' => '4', 'month' => '-', 'day' => '-'], 'served' => ['year' => '8', 'month' => '-', 'day' => '-']],
        ['no' => 24, 'sentence' => '13 ዓመት', 'deducted' => ['year' => '4', 'month' => '4', 'day' => '-'], 'served' => ['year' => '8', 'month' => '8', 'day' => '-']],
        ['no' => 25, 'sentence' => '14 ዓመት', 'deducted' => ['year' => '4', 'month' => '8', 'day' => '-'], 'served' => ['year' => '9', 'month' => '4', 'day' => '-']],
        ['no' => 26, 'sentence' => '15 ዓመት', 'deducted' => ['year' => '5', 'month' => '-', 'day' => '-'], 'served' => ['year' => '10', 'month' => '-', 'day' => '-']],
        ['no' => 27, 'sentence' => '16 ዓመት', 'deducted' => ['year' => '5', 'month' => '4', 'day' => '-'], 'served' => ['year' => '10', 'month' => '8', 'day' => '-']],
        ['no' => 28, 'sentence' => '17 ዓመት', 'deducted' => ['year' => '5', 'month' => '8', 'day' => '-'], 'served' => ['year' => '11', 'month' => '4', 'day' => '-']],
        ['no' => 29, 'sentence' => '18 ዓመት', 'deducted' => ['year' => '6', 'month' => '-', 'day' => '-'], 'served' => ['year' => '12', 'month' => '-', 'day' => '-']],
        ['no' => 30, 'sentence' => '19 ዓመት', 'deducted' => ['year' => '6', 'month' => '4', 'day' => '-'], 'served' => ['year' => '12', 'month' => '8', 'day' => '-']],
        ['no' => 31, 'sentence' => '20 ዓመት', 'deducted' => ['year' => '6', 'month' => '8', 'day' => '-'], 'served' => ['year' => '13', 'month' => '4', 'day' => '-']],
        ['no' => 32, 'sentence' => '21 ዓመት', 'deducted' => ['year' => '7', 'month' => '-', 'day' => '-'], 'served' => ['year' => '14', 'month' => '-', 'day' => '-']],
        ['no' => 33, 'sentence' => '22 ዓመት', 'deducted' => ['year' => '7', 'month' => '4', 'day' => '-'], 'served' => ['year' => '14', 'month' => '8', 'day' => '-']],
        ['no' => 34, 'sentence' => '23 ዓመት', 'deducted' => ['year' => '7', 'month' => '8', 'day' => '-'], 'served' => ['year' => '15', 'month' => '4', 'day' => '-']],
        ['no' => 35, 'sentence' => '24 ዓመት', 'deducted' => ['year' => '8', 'month' => '-', 'day' => '-'], 'served' => ['year' => '16', 'month' => '-', 'day' => '-']],
        ['no' => 36, 'sentence' => '25 ዓመት', 'deducted' => ['year' => '8', 'month' => '4', 'day' => '-'], 'served' => ['year' => '16', 'month' => '8', 'day' => '-']],
    ],
];
